export const employees = [
    {
      name: "Alice Johnson",
      role: "Software Engineer",
      department: "Engineering",
      email: "alice@example.com",
      profilePicture: "https://randomuser.me/api/portraits/med/women/86.jpg",
      yearsAtCompany: 3,
    },
    {
      name: "Bob Smith",
      role: "Product Manager",
      department: "Product",
      email: "bob@example.com",
      profilePicture: "https://randomuser.me/api/portraits/med/men/4.jpg",
      yearsAtCompany: 5,
    },
    {
      name: "Charlie Lee",
      role: "Designer",
      department: "Design",
      email: "charlie@example.com",
      profilePicture: "https://randomuser.me/api/portraits/med/men/38.jpg",
      yearsAtCompany: 1,
    },
    {
      name: "David Wilson",
      role: "Data Scientist",
      department: "Analytics",
      email: "david@example.com",
      profilePicture: "https://randomuser.me/api/portraits/med/men/32.jpg",
      yearsAtCompany: 4,
    },
    {
      name: "Eva Carter",
      role: "HR Specialist",
      department: "Human Resources",
      email: "eva@example.com",
      profilePicture: "https://randomuser.me/api/portraits/med/women/36.jpg",
      yearsAtCompany: 2,
    },
    {
      name: "Frank Thompson",
      role: "Marketing Coordinator",
      department: "Marketing",
      email: "frank@example.com",
      profilePicture: "https://randomuser.me/api/portraits/med/men/88.jpg",
      yearsAtCompany: 3,
    },
    {
      name: "Grace Davis",
      role: "UX Researcher",
      department: "Design",
      email: "grace@example.com",
      profilePicture: "https://randomuser.me/api/portraits/med/women/45.jpg",
      yearsAtCompany: 2,
    },
    {
      name: "Henry Martinez",
      role: "System Administrator",
      department: "IT",
      email: "henry@example.com",
      profilePicture: "https://randomuser.me/api/portraits/med/men/25.jpg",
      yearsAtCompany: 6,
    },
    {
      name: "Irene Taylor",
      role: "Business Analyst",
      department: "Product",
      email: "irene@example.com",
      profilePicture: "https://randomuser.me/api/portraits/med/women/15.jpg",
      yearsAtCompany: 3,
    },
    {
      name: "Jack Wilson",
      role: "Front-end Developer",
      department: "Engineering",
      email: "jack@example.com",
      profilePicture: "https://randomuser.me/api/portraits/med/men/35.jpg",
      yearsAtCompany: 1,
    },
  ];
  